### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by barbalex** [Moveo/minimize#38] opened 2015-03-30 08:10 UTC
When running gulp-minify-html I'm getting this error:

    PS C:\Users\Alexander\artendb> gulp prod
    request:  couchapp push http://user:password@127.0.0.1:5984/artendb
    [10:36:30] Using gulpfile ~\artendb\gulpfile.js
    [10:36:30] Starting 'prod'...
    [10:36:30] Starting 'browserify'...
    [10:36:30] Running 'bundle'...
    [10:36:30] Finished 'prod' after 23 ms
    [10:36:33] Finished 'bundle' in 2.57 s
    [10:36:33] Finished 'browserify' after 2.59 s
    [10:36:33] Starting 'prod_build_style'...
    [10:36:33] Starting 'prod_build_src'...
    [10:36:33] Starting 'prod_build_html'...
    C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\helpers.js:82
      return !!~list.inline.indexOf(element.name);
               ^
    RangeError: Maximum call stack size exceeded
        at String.replace (native)
        at Helpers.text (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\helpers.js:223:3
    1)
        at enter (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:120:45)
        at reduce (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:106:33)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    2:13
        at iterate (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\as
    ync.js:149:13)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:16
    0:25
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    4:17
        at close (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:137:7)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    7:13
    PS C:\Users\Alexander\artendb>

my index.html is here: https://github.com/FNSKtZH/artendb/blob/master/_attachments/index_dev.html
this used to work
a few weeks ago I updated from version 0.1.6 to 0.1.8. This is the first time I've minified since.
I updated to 1.0.1 now but the error persists.

I reported this issue at https://github.com/jonathanepollack/gulp-minify-html first (https://github.com/jonathanepollack/gulp-minify-html/issues/20) but @jonathanepollack asked me to bring it up here

**Comment by Swaagie** [comment] 2015-03-30 13:49
I'll give it a look later tonight, haven't seen this issue before. Thanks for reporting and providing context

**Comment by gsong** [comment] 2015-03-30 14:53
@Swaagie FWIW, I see the exact same thing. I haven't had time to try the new `gulp-minify-html` with an older release of `minimize` to see if that combo works.

**Comment by bprymicz** [comment] 2015-03-30 16:13
I changed the instance in gulp-minify-html to use minimize@1.2.1 and the error is gone for me.

**Comment by Swaagie** [comment] 2015-03-30 21:46
Sorry was caused by a simple missing `setImmediate/nextTick` on the async iterator, V8 had no time to clear the callstack. Fixed and released as v1.3.2

**Comment by jonathanepollack** [comment] 2015-03-30 21:46
Thanks @Swaagie for clearing this up so quickly!

**Closed by Swaagie** 2015-03-30 21:46 UTC

**Comment by barbalex** [comment] 2015-03-30 23:13
yeah, it works
thanks @Swaagie
